version: '3.8'

services:
  mysql:
    build:
      context: .
      args:
        CACHE_BUSTER: ${CACHE_BUSTER}  # змінна для примусового rebuild
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: test_user
      MYSQL_PASSWORD: Kh87Igs87HG
      MYSQL_DATABASE: employees
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./test_db:/var/lib/mysql-files  # локальна папка зі скриптами

volumes:
  mysql_data:
