version: '3.8'

services:
  mysql:
    build: .
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: test_user
      MYSQL_PASSWORD: Kh87Igs87HG
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./test_db-master:/var/lib/mysql-files

volumes:
  mysql_data:
